name: stale-blocks.csv sanity-check

on:  
  # To be able to trigger a rebuild manually by (un)assigning someone
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, reopened, synchronize, assigned, unassigned]
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sanity check
        run: python ci/sanity-check.py
