
name: stale-blocks.csv sanity-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: sanity check
        run: python ci/sanity-check.py

      - name: ckeck that additions to stale-blocks.csv do not contain a main-chain block
        run: git diff ${{ github.event.before }} ${{ github.event.after }} --no-ext-diff --unified=0 -a --no-prefix --output-indicator-new=% stale-blocks.csv | sed -n "s/^%\(.*\)$/\1/p" | python ci/no-main-chain-hash.py
